#!/usr/bin/env bash
# Logical backup for MySQL/MariaDB (mysqldump)
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "$SCRIPT_DIR/common.sh"

require_client
STAMP="$(date '+%Y%m%d_%H%M%S')"
OUT_FILE="$BACKUP_DIR/${DB_NAME}_${STAMP}.sql"

log INFO "Starting backup for database '$DB_NAME' -> $OUT_FILE"

if [[ "$MOCK_MODE" == "1" ]]; then
  cat > "$OUT_FILE" <<EOF
-- Mock logical backup generated by linux-db-ops-toolkit
-- Database: $DB_NAME
-- Timestamp: $(ts)
CREATE TABLE IF NOT EXISTS mock_health (id INT PRIMARY KEY, note VARCHAR(100));
INSERT INTO mock_health VALUES (1, 'mock backup ok');
EOF
  log OK "Mock backup written: $OUT_FILE ($(wc -c < "$OUT_FILE") bytes)"
  echo "$OUT_FILE"
  exit 0
fi

# shellcheck disable=SC2046
mysqldump $(mysql_base) \
  --single-transaction \
  --routines \
  --triggers \
  --databases "$DB_NAME" > "$OUT_FILE"

BYTES="$(wc -c < "$OUT_FILE" | tr -d ' ')"
if [[ "$BYTES" -lt 50 ]]; then
  log ERROR "Backup looks empty ($BYTES bytes)"
  exit 1
fi

log OK "Backup complete: $OUT_FILE ($BYTES bytes)"
echo "$OUT_FILE"
